manga = "日常"
author = "あらゐけいいち"
volume = 1
chapter = 1
title = "日常の1"

[[pic]]
nr = 2
page = 1
location = "shinonome house"
characters = "nano"
  [[pic.text]]
  from = "nano"
  to = "hakase"
  lines = ["すいません", "はかせ"]
  transl = "Sorry, hakase"
  [[pic.text]]
  from = "nano"
  to = "hakase"
  lines = ["朝食 は 自分 で!!", "作って 下さい!!"]
  kmap = [
    ["朝", "ちょう"],
    ["食", "しょく"],
    ["自", "じ"],
    ["分", "ぶん"],
    ["作", "つく"],
    ["下", "くだ"],
  ]
  transl = ["Breakfast is on you.", "Please make it yourself!!"]
  [[pic.text]]
  from = "naration"
  to = "audience"
  lines = ["東雲 なの", "ロボ 女子 高生"]
  kmap = [
    ["東", "しの"],
    ["雲", "のめ"],
    ["女", "じょ"],
    ["子", "し"],
    ["高", "こう"],
    ["生", "せい"],
  ]
  transl = ["Shinonome Nano", "Robot highschool girl"]
